services:
    newscoop_print_issue_manager.lifecyclesubscriber:
        class: Newscoop\PrintIssueManagerBundle\EventListener\LifecycleSubscriber
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_subscriber}

    newscoop_print_issue_manager.configure_menu_listener:
        class: Newscoop\PrintIssueManagerBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator

    newscoop_print_issue_manager.service:
        class:      Newscoop\PrintIssueManagerBundle\Services\PrintIssueManagerService
        arguments:  ["@em"]

    newscoop_print_issue_manager.article_type.service:
        class:      Newscoop\PrintIssueManagerBundle\Services\ArticleTypeConfigurationService
        arguments:  ["@em"]