services:
    newscoop_print_issue_manager.lifecyclesubscriber:
        class: Newscoop\PrintIssueManagerBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_print_issue_manager.configure_menu_listener:
        class: Newscoop\PrintIssueManagerBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator